version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4173:4173"
    links:
      - backend
    restart: always
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
