version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
