version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    network_mode: host
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    restart: always
    network_mode: host
